-- Drop tables if they already exist
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Link_social;
DROP TABLE IF EXISTS Education;
DROP TABLE IF EXISTS Language;
DROP TABLE IF EXISTS Skill;
DROP TABLE IF EXISTS Xp;
DROP TABLE IF EXISTS Cert;
DROP TABLE IF EXISTS Projects;

-- Create a Users table
CREATE TABLE Users (
    Name        TEXT NOT NULL,
    Img         TEXT,
    Email       TEXT,
    Profession  TEXT,
    Description TEXT
);

CREATE TABLE Link_social(
    Name    TEXT,
    Link    TEXT
);

CREATE TABLE Education (
    School      TEXT,
    Degree      TEXT,
    Duration    TEXT,
    Description TEXT
);

CREATE TABLE Language(
    Name    TEXT,
    lEVEL   TEXT
);

CREATE TABLE Skill(
    Name        TEXT,
    percent     Int
);

CREATE TABLE Xp(
    Company     TEXT,
    Position    TEXT,
    Duration    TEXT,
    Description TEXT
);

CREATE TABLE Cert(
    Company TEXT,
    Name    TEXT
);

CREATE TABLE Projects(
    Title       TEXT,
    Description TEXT,
    Img         TEXT,
    Link        TEXT
);

-- Insert initial projects
INSERT INTO Projects VALUES
('Inventory Control','Developed an internal inventory management system for TATA company using VBA Excel and SQL Server, improving stock tracking efficiency by 30%','https://i.postimg.cc/fb3rkzkw/image.png','https://github.com/FierSet'),
('Curriculum Vitae', 'This CV has been built in three versions, showcasing PHP, React.js, and ASP.NET MVC.','https://raw.githubusercontent.com/FierSet/Curriculum-vitae-javascript/a523207b808a81a73b8405fba02c155cbfa438ff/image.png','http://miguelaoz.atwebpages.com/CV-List.php'),
('Xor cypher', 'Made in C#, encript the information using the method XOR.', 'https://raw.githubusercontent.com/FierSet/encriptaci-n-xor/d7a71f567908c2fe6c33ae1926d0393c1571ad18/image.png', 'https://github.com/FierSet/encriptaci-n-xor'),
('Mobile App', 'Created for Android using Java, it allows for hiring professionals through the app, creating contracts and saving them in a database.', 'https://raw.githubusercontent.com/FierSet/Hire-Now/8eaab7381dc33f46af7224ad01510bf16421bf93/image.png', 'https://github.com/FierSet/Hire-Now'),
('E-commerce', 'E-commerce made in React.JS using a SQL Server as database.', 'https://raw.githubusercontent.com/FierSet/Inmobiliarias/fef7de2ea18c2367f949cd6737060a7aac6cae1e/image.png', 'https://github.com/FierSet/Inmobiliarias'),
('Cesar cypher','Made in C#, encript the information using the method Cesar, also uses brute force to unencrypted.','https://raw.githubusercontent.com/FierSet/encriptacion_cesar/6bb407126c5f1c8e11c8fab6e890456c4073e995/image.png','https://github.com/FierSet/encriptacion_cesar');

-- Insert initial users
INSERT INTO Users VALUES
('Miguel Angel', 'https://www.dropbox.com/scl/fi/i3mzl9ujlsxab45co6bl2/mi_imagen.jpg?rlkey=oyh2tsbvh55ol9avu6qf7nqnb&dl=1' ,'miguel-011998@hotmail.com', 'System Engineer', 
'Programmer with experience in C#, .NET, and front-end technologies such as JavaScript and CSS. Developed small web applications and automated internal tasks using VBA and PowerShell. Currently deepening expertise in ASP.NET MVC and SQL. Passionate about clean code, software quality, and collaborative development.');

INSERT INTO Link_social VALUES
('Github', 'https://github.com/FierSet'),
('Linkedin', 'https://www.linkedin.com/in/miguelangelortegazacarias/'),
('Main web', 'http://miguelaoz.atwebpages.com/CV-List.php');

INSERT INTO Education VALUES
('ITQ (Instituto Tecnológicode Querétaro)', 'Computer systems engineer', '2017 - 2023', 'Programming & software development, Networking & operating systems, Database design & administration, Systems analysis & problem-solving, Cybersecurity principles, Cloud computing & virtualization, Communication & teamwork'),
('CeCyTEC','Electronics Technician.','2013 - 2016', 'Circuit analysis and troubleshooting, Soldering and PCB repair. Use of measurement and diagnostic tools, Knowledge of microcontrollers and embedded systems, Reading electrical/electronic schematics, Problem-solving and attention to detail');

INSERT INTO Language VALUES
('Spanish', 'Native'),
('English','B1');

INSERT INTO Skill VALUES
('C/C++', 70), ('C#', 80), ('JAVA', 70), ('VBA', 80), ('PHP', 70), ('SQL', 90), ('SQL/PL', 60), ('Python', 70), ('PowerShell', 60),
('Full-Stack', 60), ('Git/GitHub', 70), ('Azure DevOps', 70), ('Linux', 80);

INSERT INTO Xp VALUES
('TATA Consultancy Services', 
'Infraestructure Eng.', 
'2023-2025', 
'Implementation of devices (desktop, laptop, switches and servers) inventory control with database SQL Server, SSMS, Visual basic, C#, using Visual basic to generate reports in excel in Tata consultancy services.
Manage status and control of devices (Laptops, Desktop, Switches and Servers) using database SQL.
Resolved Blue Screen Error Generated by CrowdStrike:
Successfully restored full functionality and stability to affected systems, improving overall uptime by 20%.');

INSERT INTO Cert VALUES
('freecodecamp', 'JavaScript Algorithms and Data Structures.'),
('freecodecamp', 'Front End Development Libraries'),
('freecodecamp','Responsive Web Design'),
('GOOGLE','Mobile App Development'),
('GOOGLE','Google Cloud Computing Foundations ACADEMY'),
('GOOGLE','Perform Foundational Data, ML, and AI Tasks in Google Cloud (2022)'),
('GOOGLE','Create and Manage Cloud Resources (2022)'),
('GOOGLE','Google Cloud Computing Foundations: Data, ML, and AI in Google Cloud (2022)'),
('GOOGLE','Perform Foundational Infrastructure Tasks in Google Cloud (2022)'),
('GOOGLE','Build and Secure Networks in Google Cloud (2022)'),
('GOOGLE','Google Cloud Computing Foundations: Networking & Security in Google Cloud (2022)'),
('GOOGLE','Google Cloud Computing Foundations: Infrastructure in Google Cloud (2022)'),
('GOOGLE','Google Cloud Computing Foundations: Cloud Computing Fundamentals (2022)'),
('GOOGLE','Google Cloud Fundamentals for Azure Professionals: Core Infrastructure(2022)'),
('GOOGLE','Google Cloud Fundamentals for AWS Professionals (2022)'),
('GOOGLE','Google Cloud Fundamentals: Core Infrastructure (2022)'),
('GOOGLE','Google Cloud Big Data and Machine Learning Fundamentals (2022)'),
('GOOGLE','Google Cloud Fundamentals: Core Infrastructure (2022)'),
('CISCO','CCNAv7: Linux Essentials'),
('CISCO','CCNAv7: Programming Essentials in C'),
('CISCO','CCNAv7: Enterprise Networking, Security, and Automation'),
('CISCO','CCNAv7: Switching, Routing, and Wireless Essentials'),
('CISCO','CCNAv7: Introducción a Redes');